namespace SoftWC.Models
{
    public enum TipoClienteEnum
    {
        CORPORATIVOS, //REFERIDO A EMPRESAS PRIVADAS, EN DIVERSAS, 
        RESIDENCIALES, //PERSONAS NATURALES, FAIMILIAS, 
        INSTITUCIONALES // ENTIDADES DEL ESTADO, GOBIERNO, MUNICIPIOS, ETC
    }
}